# Generated by Django 4.0.1 on 2022-01-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(help_text='Keep it brief.', max_length=30)),
                ('description', models.CharField(help_text='Full Description(OR short).', max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
